export function getRandomMessageTips(n: number) {
    return messageTipsTexts.sort(() => Math.random() - Math.random()).slice(0, n);
}

export const messageTipsTexts: string[] = [
    "Tell me a joke about robots.",
    "What's the meaning of life?",
    "Explain quantum physics in simple terms.",
    "Compose a haiku about the ocean.",
    "How do I bake chocolate chip cookies?",
    "Translate 'Hello, how are you?' to French.",
    "What happened during the Renaissance?",
    "Suggest a good mystery novel.",
    "Can you solve this riddle for me?",
    "Write a short story about dragons.",
    "Teach me some Spanish phrases.",
    "What's the capital of Australia?",
    "Give me some meditation tips.",
    "Who invented the telephone?",
    "What's the latest tech news?",
    "Define the theory of relativity.",
    "Help me plan a trip to Japan.",
    "Describe the process of photosynthesis.",
    "Tell me about Greek mythology.",
    "What's a healthy breakfast idea?",
    "Recommend a sci-fi movie.",
    "How does blockchain technology work?",
    "What's the best way to learn guitar?",
    "Explain the causes of World War II.",
    "Can you write a poem about love?",
    "What are the benefits of yoga?",
    "How do I improve my public speaking?",
    "What's the weather like today?",
    "Tell me a fun fact about space.",
    "How can I reduce stress?",
    "What's the history of the Internet?",
    "Teach me about artificial intelligence.",
    "Suggest some exercises for beginners.",
    "How does a solar eclipse occur?",
    "What's the best way to save money?",
    "Describe the life cycle of a butterfly.",
    "Tell me a pun involving food.",
    "What's an interesting philosophical question?",
    "How do I write a resume?",
    "Explain the concept of supply and demand.",
    "What are some popular Italian dishes?",
    "Can you recommend a classic book?",
    "What's an effective study technique?",
    "Tell me about the Big Bang theory.",
    "How do I start learning programming?",
    "What's the tallest mountain on Earth?",
    "Share tips for time management.",
    "Explain how photosynthesis works.",
    "What is cybersecurity?",
    "Tell me a motivational quote.",
    "How does gravity work?",
    "Describe the process of evaporation.",
    "What's an interesting animal fact?",
    "Help me understand algebra basics.",
    "What's the significance of the moon?",
    "Teach me about renewable energy.",
    "What's the best way to learn a language?",
    "Explain the water cycle.",
    "What are some famous art movements?",
    "Tell me a historical mystery.",
    "How do airplanes fly?",
    "What's the origin of the universe?",
    "Recommend a documentary to watch.",
    "Explain the concept of democracy.",
    "How can I improve my writing skills?",
    "Tell me about ancient Egypt.",
    "What's a good way to stay healthy?",
    "Describe the function of the heart.",
    "Explain the law of conservation of energy.",
    "What's an interesting fact about music?",
    "How do I grow a garden?",
    "What's the importance of sleep?",
    "Tell me about the human brain.",
    "What's the history of vaccines?",
    "How does the stock market work?",
    "Explain the theory of evolution.",
    "Recommend a comedy TV show.",
    "How do I make homemade pasta?",
    "What's an easy science experiment?",
    "Tell me about the solar system.",
    "What's the significance of art?",
    "How can I be more productive?",
    "Explain what black holes are.",
    "What's the difference between viruses and bacteria?",
    "Tell me about the Great Wall of China.",
    "How do I improve my memory?",
    "What's the best way to relax?",
    "Explain the importance of recycling.",
    "Tell me an interesting fact about whales.",
    "What's the history of computers?",
    "How can I learn to code?",
    "Explain what renewable resources are.",
    "What's an easy recipe for beginners?",
    "Tell me about famous philosophers.",
    "How do I start meditating?",
    "What's the significance of the pyramids?",
    "Explain the basics of photography.",
    "What's the history of jazz music?",
    "How does the human eye work?",
    "Tell me about famous inventors.",
    "What's a fun outdoor activity?",
    "Explain the process of digestion.",
    "How can I develop better habits?",
    "Tell me about the history of books.",
    "What's an interesting math concept?",
    "How do I play chess?",
    "Explain the importance of biodiversity.",
    "What's a good way to start exercising?",
    "Tell me about the Seven Wonders.",
    "How do I manage my time effectively?",
    "Explain what climate change is.",
    "What's the history of the Olympics?",
    "Tell me a fun science fact.",
    "How does the immune system work?",
    "Explain the concept of mindfulness.",
    "What's an interesting fact about birds?",
    "How can I improve my diet?",
    "Tell me about classical music.",
    "What's the importance of teamwork?",
    "Explain how computers process data.",
    "How do I start a blog?",
    "Tell me about the history of cinema.",
    "What's a good way to learn math?",
    "Explain the basics of economics.",
    "How does the circulatory system work?",
    "Tell me about famous explorers.",
    "What's an interesting fact about the ocean?",
    "How do I create a budget?",
    "Explain the principles of design.",
    "What's the importance of education?",
    "Tell me about space exploration.",
    "How can I improve my sleep quality?",
    "Explain the science behind rainbows.",
    "What's an easy way to learn history?",
    "Tell me about famous painters.",
    "How do I write a short story?",
    "Explain the concept of probability.",
    "What's an interesting fact about trees?",
    "How can I learn to draw?",
    "Tell me about different musical instruments.",
    "What's the best way to study?",
    "Explain how vaccines work.",
    "How do I improve my vocabulary?",
    "Tell me about the history of sports.",
    "What's an interesting fact about insects?",
    "How can I learn to sing?",
    "Explain the basics of astronomy.",
    "What's the importance of art in society?",
    "Tell me about the human skeleton.",
    "How do I start learning photography?",
    "Explain what DNA is.",
    "What's an interesting fact about mountains?",
    "How can I improve my handwriting?",
    "Tell me about famous writers.",
    "What's the history of theater?",
    "Explain the process of fermentation.",
    "How do I learn a new skill quickly?",
    "Tell me about renewable energy sources.",
    "What's an interesting fact about dolphins?",
    "How can I be more creative?",
    "Explain the basics of machine learning.",
    "What's the importance of critical thinking?",
    "Tell me about famous architects.",
    "How do I improve my listening skills?",
    "Explain the process of cloud formation.",
    "What's an interesting fact about volcanoes?",
    "How can I learn better?",
    "Tell me about the history of dance.",
    "What's the significance of storytelling?",
    "Explain the basics of genetics.",
    "How do I stay motivated?",
    "Tell me about famous historical figures.",
    "What's an interesting fact about planets?",
    "How can I improve my concentration?",
    "Explain what ecosystems are.",
    "What's the importance of communication?",
    "Tell me about different world cultures.",
    "How do I learn to play an instrument?",
    "Explain the basics of geology.",
    "What's an interesting fact about stars?",
    "How can I improve my leadership skills?",
    "Tell me about the history of medicine.",
    "What's the importance of ethics?",
    "Explain the process of evolution.",
    "How do I start coding in Python?",
    "Tell me about famous composers.",
    "How can I manage anxiety?",
    "Explain the basics of marketing.",
    "What's the importance of innovation?",
    "Tell me about famous scientists.",
    "How do I write a poem?",
    "Explain what renewable energy is.",
    "What's an interesting fact about the brain?",
    "How can I learn about astronomy?",
    "Tell me about global warming.",
    "What's the importance of sustainability?",
    "Explain the basics of robotics.",
    "How do I improve my negotiation skills?",
    "Tell me about the human digestive system.",
    "What's an interesting fact about reptiles?",
    "Explain the concept of time dilation.",
    "What's the importance of empathy?",
    "Tell me about famous entrepreneurs.",
    "How do I practice mindfulness?",
    "Explain how batteries work.",
    "What's an interesting fact about lightning?",
    "How can I improve my presentation skills?",
    "Tell me about different writing styles.",
    "What's the history of mathematics?",
    "Explain the basics of web development.",
    "How do I start learning to paint?",
    "Tell me about marine life.",
    "What's an interesting fact about galaxies?",
    "How can I develop emotional intelligence?",
    "Explain the concept of the Internet of Things.",
    "What's the importance of cultural diversity?",
    "Tell me about ancient civilizations.",
    "How do I improve my critical thinking?",
    "Explain what neurons are.",
    "What's an interesting fact about penguins?",
    "How can I learn graphic design?",
    "Tell me about the history of flight.",
    "Explain the basics of calculus.",
    "How do I write a cover letter?",
    "Tell me about famous landmarks.",
    "What's an interesting fact about comets?",
    "How can I learn sign language?",
    "Explain the process of natural selection.",
    "What's the importance of mental health?",
    "Tell me about famous poets.",
    "How do I practice active listening?",
    "Explain the basics of data science.",
    "What's an interesting fact about fungi?",
    "How can I improve my drawing skills?",
    "Tell me about the history of photography.",
    "Explain how GPS works.",
    "How do I start learning a new language?",
    "What's an interesting fact about the Sahara Desert?",
    "How can I improve my cooking skills?",
    "Explain the basics of chemistry.",
    "What's the importance of water conservation?",
    "Tell me about famous filmmakers.",
    "How do I prepare for an interview?",
    "Explain how sound travels.",
    "What's an interesting fact about meteors?",
    "How can I develop better communication skills?",
    "Tell me about different art styles.",
    "Explain the basics of circuits.",
    "How do I improve my problem-solving skills?",
    "Tell me about famous sculptures.",
    "What's an interesting fact about marsupials?",
    "How do I start a podcast?",
    "Tell me about the history of video games.",
    "How can I improve my decision-making?",
    "Explain the process of mitosis.",
    "What's the importance of the ozone layer?",
    "Tell me about famous athletes.",
    "How do I learn about investments?",
    "Explain the basics of trigonometry.",
    "How can I practice gratitude?",
    "Tell me about famous historical events.",
    "What's the importance of good posture?",
    "Explain how Wi-Fi works.",
    "How do I improve my chess skills?",
    "Tell me about famous festivals.",
    "What's an interesting fact about glaciers?",
    "How can I develop self-discipline?",
    "Explain the basics of cloud computing.",
    "What's the importance of friendship?",
    "How do I write a business plan?",
    "Explain how magnets work.",
    "What's an interesting fact about jellyfish?",
    "How can I practice self-care?",
    "Explain the process of respiration.",
    "How do I improve my emotional intelligence?",
    "Tell me about different dance styles.",
    "How can I learn to code in JavaScript?",
    "Explain the basics of cryptocurrency.",
    "What's the importance of goal setting?",
    "How do I improve my teamwork skills?",
    "Explain the basics of environmental science."
]